import type { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: 1,
    category: 'Waffles',
    name: 'Classic Belgian Waffle',
    description: 'A light, crispy waffle served with powdered sugar and maple syrup.',
    price: 8.50,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'belgian waffle',
    ingredients: ['Flour', 'Egg', 'Milk', 'Sugar', 'Butter'],
    calories: 350,
  },
  {
    id: 2,
    category: 'Waffles',
    name: 'Chocolate Dream Waffle',
    description: 'Our signature waffle drizzled with rich Belgian chocolate sauce, topped with chocolate chips and whipped cream.',
    price: 12.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chocolate waffle',
    ingredients: ['Flour', 'Egg', 'Milk', 'Cocoa Powder', 'Chocolate Sauce', 'Chocolate Chips'],
    calories: 550,
  },
  {
    id: 3,
    category: 'Waffles',
    name: 'Fruity Paradise Waffle',
    description: 'A vibrant waffle topped with fresh seasonal fruits like strawberries, bananas, and blueberries, with a side of cream.',
    price: 13.50,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fruit waffle',
    ingredients: ['Flour', 'Egg', 'Milk', 'Strawberries', 'Bananas', 'Blueberries'],
    calories: 450,
  },
  {
    id: 4,
    category: 'Waffles',
    name: 'Savory Chicken & Waffle',
    description: 'A Southern classic! Crispy fried chicken served on top of our Belgian waffle, with a side of spicy maple syrup.',
    price: 15.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken waffle',
    ingredients: ['Flour', 'Egg', 'Milk', 'Chicken', 'Spices', 'Maple Syrup'],
    calories: 750,
  },
  {
    id: 5,
    category: 'Drinks',
    name: 'Espresso',
    description: 'A strong, concentrated coffee brewed by forcing a small amount of nearly boiling water through finely-ground coffee beans.',
    price: 3.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'espresso shot',
    ingredients: ['Coffee Beans', 'Water'],
    calories: 5,
  },
  {
    id: 6,
    category: 'Drinks',
    name: 'Latte',
    description: 'A coffee drink made with espresso and steamed milk, topped with a light layer of foam.',
    price: 4.50,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'latte art',
    ingredients: ['Espresso', 'Steamed Milk'],
    calories: 150,
  },
  {
    id: 7,
    category: 'Drinks',
    name: 'Fresh Orange Juice',
    description: '100% freshly squeezed orange juice, packed with Vitamin C.',
    price: 5.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'orange juice',
    ingredients: ['Oranges'],
    calories: 120,
  },
  {
    id: 8,
    category: 'Sides',
    name: 'Scoop of Ice Cream',
    description: 'Add a scoop of your favorite ice cream. Choose from Vanilla, Chocolate, or Strawberry.',
    price: 3.50,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'icecream scoop',
    ingredients: ['Milk', 'Cream', 'Sugar', 'Flavoring'],
    calories: 200,
  },
  {
    id: 9,
    category: 'Sides',
    name: 'Side of Bacon',
    description: 'Three crispy strips of savory bacon.',
    price: 4.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'crispy bacon',
    ingredients: ['Pork'],
    calories: 150,
  },
];
